<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3bugyus\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3bugyus/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3bugyus.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3bugyus\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3bugyus\appProdProjectContainer([
    'container.build_hash' => '3bugyus',
    'container.build_id' => 'c7acd8b8',
    'container.build_time' => 1689963386,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3bugyus');
