<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3pubvbn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3pubvbn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3pubvbn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3pubvbn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3pubvbn\appDevDebugProjectContainer([
    'container.build_hash' => '3pubvbn',
    'container.build_id' => 'e4d1ae11',
    'container.build_time' => 1690210000,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3pubvbn');
